/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.panelData;

import Manegement.Learn.learnAll;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import user.Connect;

/**
 *
 * @author HP
 */
public class Learn extends javax.swing.JPanel {

    private JPanel childPanel;
    private JFrame frame;

    DefaultTableModel tbn = new DefaultTableModel();
    Connect a = new Connect();
    Connection con = a.getConnection();
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    String fPath = null;
    byte[] img_DATA;

    private String username;

    public Learn(String username) {
        initComponents();
        this.username = username;
        getConnection();
        loadTest();
        LoadBG();
        Topic1();
        Topic2();
        Topic3();
        Topic4();
    }

    public void Topic1() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Animals\\Hamster.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lbl1.setIcon(image);
    }

    public void Topic2() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Bugs and insects\\Grasshopper.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lbl2.setIcon(image);
    }

    public void Topic3() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Colors\\Yellow.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lbl3.setIcon(image);
    }

    public void Topic4() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Fruits\\Apple.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lbl4.setIcon(image);
    }

    public void getConnection() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=duan1;user=sa;password=sa2008");
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery("Select * from TuVung where TenChuDe not in ('Random')");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }

    public void loadTest() {
        try {
            rs.first();
            lblVocabulary.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH));
            lblImg.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void LoadBG() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Background\\18.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(1392, 500, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblBg.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        lblPrevious = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblVocabulary = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        right = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1392, 872));
        setLayout(new java.awt.BorderLayout());

        top.setBorder(null);
        top.setOpaque(false);
        top.setPreferredSize(new java.awt.Dimension(1392, 372));
        top.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setPreferredSize(new java.awt.Dimension(1200, 100));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HỌC TỪ VỰNG");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1384, 96));

        jSeparator2.setBackground(new java.awt.Color(0, 120, 255));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator2.setOpaque(true);
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 100, 5));

        top.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 272));

        lblPrevious.setBackground(new java.awt.Color(204, 216, 224));
        lblPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_64px.png"))); // NOI18N
        lblPrevious.setOpaque(true);
        lblPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPreviousMouseClicked(evt);
            }
        });

        lblNext.setBackground(new java.awt.Color(204, 216, 224));
        lblNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next_64px.png"))); // NOI18N
        lblNext.setOpaque(true);
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });

        lblVocabulary.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        lblVocabulary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVocabulary, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(lblNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblVocabulary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        top.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(204, 216, 224));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(688, 272));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("BẮT ĐẦU");
        jButton1.setPreferredSize(new java.awt.Dimension(170, 45));

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("THÀNH TÍCH");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(217, 217, 217))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        top.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(top, java.awt.BorderLayout.PAGE_START);

        right.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        right.setPreferredSize(new java.awt.Dimension(1392, 500));
        right.setLayout(new java.awt.BorderLayout());

        left.setPreferredSize(new java.awt.Dimension(1392, 500));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setOpaque(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(1200, 500));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel16.setLayout(flowLayout1);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 140, 30, 140));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(1392, 500));
        jPanel6.setLayout(new java.awt.GridLayout(2, 3, 50, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setAutoscrolls(true);
        lbl1.setOpaque(true);
        lbl1.setPreferredSize(new java.awt.Dimension(200, 16));
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });
        jPanel1.add(lbl1, java.awt.BorderLayout.CENTER);

        jLabel5.setBackground(new java.awt.Color(20, 17, 109));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Chủ đề 1: Động vật");
        jLabel5.setAutoscrolls(true);
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel1.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setAutoscrolls(true);
        lbl2.setOpaque(true);
        lbl2.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel2.add(lbl2, java.awt.BorderLayout.CENTER);

        jLabel6.setBackground(new java.awt.Color(20, 17, 109));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Chủ đề 2: Bọ và côn trùng");
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel2.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel3.setLayout(new java.awt.BorderLayout());

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setAutoscrolls(true);
        lbl3.setOpaque(true);
        lbl3.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel3.add(lbl3, java.awt.BorderLayout.CENTER);

        jLabel7.setBackground(new java.awt.Color(20, 17, 109));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Chủ đề 3: Màu sắc");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel3.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel7.setLayout(new java.awt.BorderLayout());

        lbl4.setBackground(new java.awt.Color(255, 255, 255));
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setAutoscrolls(true);
        lbl4.setOpaque(true);
        lbl4.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel7.add(lbl4, java.awt.BorderLayout.CENTER);

        jLabel8.setBackground(new java.awt.Color(20, 17, 109));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Chủ đề 4: Trái cây");
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel7.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel7);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel9.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel9.setLayout(new java.awt.BorderLayout());

        lbl5.setBackground(new java.awt.Color(255, 255, 255));
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setAutoscrolls(true);
        lbl5.setOpaque(true);
        lbl5.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel9.add(lbl5, java.awt.BorderLayout.CENTER);

        jLabel9.setBackground(new java.awt.Color(20, 17, 109));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Chủ đề 3: Màu sắc");
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel9.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel10.setLayout(new java.awt.BorderLayout());

        lbl6.setBackground(new java.awt.Color(255, 255, 255));
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setAutoscrolls(true);
        lbl6.setOpaque(true);
        lbl6.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel10.add(lbl6, java.awt.BorderLayout.CENTER);

        jLabel10.setBackground(new java.awt.Color(20, 17, 109));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Chủ đề 3: Màu sắc");
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel10.add(jLabel10, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel10);

        jPanel16.add(jPanel6);

        left.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1388, 496));

        lblBg.setBackground(new java.awt.Color(255, 255, 255));
        lblBg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBg.setOpaque(true);
        left.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1392, 500));

        right.add(left, java.awt.BorderLayout.CENTER);

        add(right, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        try {
            if (!rs.isLast()) {
                rs.next();
                lblVocabulary.setText(rs.getString("TuVung"));
                byte[] img = rs.getBytes("HinhAnh");
                ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH));
                lblImg.setIcon(imgIcon);
                img_DATA = img;
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPreviousMouseClicked
        try {
            if (!rs.isFirst()) {
                rs.previous();
                lblVocabulary.setText(rs.getString("TuVung"));
                byte[] img = rs.getBytes("HinhAnh");
                ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH));
                lblImg.setIcon(imgIcon);
                img_DATA = img;
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_lblPreviousMouseClicked

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked
        learnAll q = new learnAll();
        q.setVisible(true);
    }//GEN-LAST:event_lbl1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblPrevious;
    private javax.swing.JLabel lblVocabulary;
    private javax.swing.JPanel left;
    private javax.swing.JPanel right;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
