/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import user.Connect;

/**
 *
 * @author HP
 */
public class panelquiz1 extends javax.swing.JPanel {

    DefaultTableModel tbn = new DefaultTableModel();
    Connect a = new Connect();
    Connection con = a.getConnection();
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    String fPath = null;
    byte[] img_DATA;

    ButtonGroup bg = new ButtonGroup();

    Timer t, time;
    int cong;

    int counter = 0;
    Boolean isIT = false;

    int point = 0;

    public panelquiz1() {
        initComponents();
        topicCBB();
        getConnection();
//        loadInfDKT();
//        loadInfUser();
        //test();
    }

    public void getConnection() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=duan1;user=sa;password=sa2008");
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery("Select TOP 11 * from cauhoi where chude = 'Bugs and insects'");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }

    public void loadchay() {
        t = new Timer(300, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cong++;
                ProgressBar1.setValue(cong);
                if (cong == 100) {
                    t.stop();
                }
            }
        });
        t.start();
    }

    public void topicCBB() {
        try {
            String sql = "Select DISTINCT ChuDe from CauHoi ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

//            //Tạo 1 DefaultComboboxModel
//            DefaultComboBoxModel modelID = (DefaultComboBoxModel) cbbID.getModel();
//            modelID.removeAllElements(); //Xóa hết dữ liệu trong combobox
            while (rs.next()) {
                cbbTopic.addItem(rs.getString("ChuDe"));
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Top = new javax.swing.JPanel();
        cbbTopic = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblSumTime = new javax.swing.JLabel();
        lblSumQuiz = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        ProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        rdbOption1 = new javax.swing.JRadioButton();
        rdbOption2 = new javax.swing.JRadioButton();
        rdbOption3 = new javax.swing.JRadioButton();
        rdbOption4 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        lblMaCH = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblMaDKT = new javax.swing.JLabel();
        lblMaND = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblSumMark = new javax.swing.JLabel();
        lblSumPoitn = new javax.swing.JLabel();
        lblTenChuDe = new javax.swing.JLabel();
        Option = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblCau1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCau10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 831));

        Top.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 1, true));

        cbbTopic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTopic.setMaximumRowCount(3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Số câu đúng: ");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 35));

        btnStart.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnStart.setText("BẮT ĐẦU");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Thời gian: ");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Chọn chủ đề kiểm tra:");

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDate.setOpaque(true);
        lblDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblDatePropertyChange(evt);
            }
        });

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTime.setOpaque(true);

        lblSumTime.setBackground(new java.awt.Color(255, 255, 255));
        lblSumTime.setOpaque(true);

        lblSumQuiz.setBackground(new java.awt.Color(255, 255, 255));
        lblSumQuiz.setOpaque(true);

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addComponent(cbbTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStart)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(lblSumQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSumTime, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSumQuiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSumTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );

        Main.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        Main.setLayout(new java.awt.BorderLayout(10, 10));

        Header.setPreferredSize(new java.awt.Dimension(0, 30));
        Header.setLayout(new java.awt.BorderLayout());

        ProgressBar1.setForeground(new java.awt.Color(0, 255, 51));
        ProgressBar1.setValue(10);
        ProgressBar1.setPreferredSize(new java.awt.Dimension(146, 30));
        Header.add(ProgressBar1, java.awt.BorderLayout.PAGE_START);

        Main.add(Header, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(173, 170));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        rdbOption1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbOption1);
        rdbOption1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rdbOption1.setText("Đáp án 1");
        rdbOption1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdbOption1.setIconTextGap(10);
        rdbOption1.setMargin(new java.awt.Insets(2, 50, 2, 2));
        rdbOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOption1ActionPerformed(evt);
            }
        });
        jPanel2.add(rdbOption1);

        rdbOption2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbOption2);
        rdbOption2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rdbOption2.setText("Đáp án 2");
        rdbOption2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdbOption2.setIconTextGap(10);
        rdbOption2.setMargin(new java.awt.Insets(2, 50, 2, 2));
        rdbOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOption2ActionPerformed(evt);
            }
        });
        jPanel2.add(rdbOption2);

        rdbOption3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbOption3);
        rdbOption3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rdbOption3.setText("Đáp án 3");
        rdbOption3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdbOption3.setIconTextGap(10);
        rdbOption3.setMargin(new java.awt.Insets(2, 50, 2, 2));
        rdbOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOption3ActionPerformed(evt);
            }
        });
        jPanel2.add(rdbOption3);

        rdbOption4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbOption4);
        rdbOption4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rdbOption4.setText("Đáp án 4");
        rdbOption4.setIconTextGap(10);
        rdbOption4.setInheritsPopupMenu(true);
        rdbOption4.setMargin(new java.awt.Insets(2, 50, 2, 2));
        rdbOption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOption4ActionPerformed(evt);
            }
        });
        jPanel2.add(rdbOption4);

        Main.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(594, 300));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));
        jPanel1.add(lblImg, java.awt.BorderLayout.CENTER);

        lblMaCH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaCH.setText("      CÂU ");
        lblMaCH.setPreferredSize(new java.awt.Dimension(74, 40));
        jPanel1.add(lblMaCH, java.awt.BorderLayout.PAGE_START);

        Main.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mã đề kiểm tra:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Mã người dùng: ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Họ và Tên:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Số câu đã làm:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("Tổng điểm");

        lblMaDKT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblMaND.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblHoTen.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblSumMark.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblSumPoitn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblTenChuDe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSumPoitn, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaDKT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblTenChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSumMark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaDKT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTenChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaND, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSumMark, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSumPoitn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Main.add(jPanel6, java.awt.BorderLayout.WEST);

        Option.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 300));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 20);
        flowLayout1.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout1);

        lblCau1.setBackground(new java.awt.Color(255, 255, 255));
        lblCau1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCau1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCau1.setText("Câu 1");
        lblCau1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        lblCau1.setOpaque(true);
        lblCau1.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(lblCau1);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Câu 2");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(jLabel7);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Câu 3");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jLabel15.setOpaque(true);
        jLabel15.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(jLabel15);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Câu 4");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(jLabel14);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Câu 5");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jLabel13.setOpaque(true);
        jLabel13.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(jLabel13);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Câu 6");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(jLabel12);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Câu 7");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(jLabel11);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Câu 8");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(jLabel10);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Câu 9");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.add(jLabel9);

        lblCau10.setBackground(new java.awt.Color(255, 255, 255));
        lblCau10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCau10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCau10.setText("Câu 10");
        lblCau10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        lblCau10.setOpaque(true);
        lblCau10.setPreferredSize(new java.awt.Dimension(70, 30));
        lblCau10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCau10MouseClicked(evt);
            }
        });
        jPanel4.add(lblCau10);

        Option.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 40);
        flowLayout2.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout2);

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnNext.setText("Next");
        btnNext.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel3.add(btnNext);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Submit");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        Option.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Option, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Option, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            if (!rs.isLast()) {
                rs.next();
                lblMaCH.setText("Câu " + rs.getString("MaCH") + ":");
                rdbOption1.setText(rs.getString("DapAnA"));
                rdbOption2.setText(rs.getString("DapAnB"));
                rdbOption3.setText(rs.getString("DapAnC"));
                rdbOption4.setText(rs.getString("DapAnD"));
                byte[] img = rs.getBytes(7);
                ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH));
                lblImg.setIcon(imgIcon);
                img_DATA = img;
            }
            rdbOption1.setSelected(false);
            rdbOption2.setSelected(false);
            rdbOption3.setSelected(false);
            rdbOption4.setSelected(false);

            rdbOption1.setEnabled(true);
            rdbOption2.setEnabled(true);
            rdbOption3.setEnabled(true);
            rdbOption4.setEnabled(true);

            rdbOption1.setBackground(Color.white);
            rdbOption2.setBackground(Color.white);
            rdbOption3.setBackground(Color.white);
            rdbOption4.setBackground(Color.white);

            rdbOption1.setSelected(false);
//            rdbOption2.setSelected(false);
//            rdbOption3.setSelected(false);
//            rdbOption4.setSelected(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        loadTest();
        loadchay();
    }//GEN-LAST:event_btnStartActionPerformed

    private void lblCau10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCau10MouseClicked
        try {
            rs.last();
            lblMaCH.setText("Câu " + rs.getString(1) + ":");
            rdbOption1.setText(rs.getString(3));
            rdbOption2.setText(rs.getString(4));
            rdbOption3.setText(rs.getString(5));
            rdbOption4.setText(rs.getString(6));
            byte[] img = rs.getBytes(7);
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH));
            lblImg.setIcon(imgIcon);
            img_DATA = img;
            if (rdbOption1.equals(rs.getString(8))) {
                rdbOption1.setBackground(Color.green);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_lblCau10MouseClicked

    private void lblDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblDatePropertyChange

    }//GEN-LAST:event_lblDatePropertyChange

    private void rdbOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOption1ActionPerformed
        if (rdbOption1.isSelected() == true) {
            try {
                //String MaCH = rs.getString("MaCH")
                String answer = rs.getString("CauTraLoi");
                String option1 = rs.getString("DapAnA");
                lblSumTime.setText(rs.getString("CauTraLoi"));
                lblSumQuiz.setText(rs.getString("DapAnA"));

                if (option1.trim().equals(answer)) {
                    rdbOption1.setBackground(Color.green);
                    point += 1;
                }
            } catch (Exception e) {
            }
            rdbOption2.setEnabled(false);
            rdbOption3.setEnabled(false);
            rdbOption4.setEnabled(false);
        }
    }//GEN-LAST:event_rdbOption1ActionPerformed

    private void rdbOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOption2ActionPerformed
        if (rdbOption2.isSelected() == true) {
            try {
                String answer = rs.getString("CauTraLoi");
                String option2 = rs.getString("DapAnB");
                lblSumTime.setText(rs.getString("CauTraLoi"));
                lblSumQuiz.setText(rs.getString("DapAnB"));
                if (option2.trim().equals(answer)) {
                    rdbOption2.setBackground(Color.green);
                    point += 1;
                }
            } catch (Exception e) {
            }
            rdbOption1.setEnabled(false);
            rdbOption3.setEnabled(false);
            rdbOption4.setEnabled(false);
        }
    }//GEN-LAST:event_rdbOption2ActionPerformed

    private void rdbOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOption3ActionPerformed
        if (rdbOption3.isSelected() == true) {
            try {
                String answer = rs.getString("CauTraLoi");
                String option3 = rs.getString("DapAnC");
                lblSumTime.setText(rs.getString("CauTraLoi"));
                lblSumQuiz.setText(rs.getString("DapAnC"));
                if (option3.trim().equals(answer)) {
                    rdbOption3.setBackground(Color.green);
                    point += 1;
                }
            } catch (Exception e) {
            }
            rdbOption1.setEnabled(false);
            rdbOption2.setEnabled(false);
            rdbOption4.setEnabled(false);
        }
    }//GEN-LAST:event_rdbOption3ActionPerformed

    private void rdbOption4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOption4ActionPerformed
        if (rdbOption4.isSelected() == true) {
            try {
                String answer = rs.getString("CauTraLoi");
                String option4 = rs.getString("DapAnD");
                lblSumTime.setText(rs.getString("CauTraLoi"));
                lblSumQuiz.setText(rs.getString("DapAnD"));
                if (option4.trim().equals(answer)) {
                    rdbOption4.setBackground(Color.green);
                    point += 1;
                }
            } catch (Exception e) {
            }
            rdbOption1.setEnabled(false);
            rdbOption2.setEnabled(false);
            rdbOption3.setEnabled(false);
        }
    }//GEN-LAST:event_rdbOption4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String sum = Integer.toString(point);
        lblSumPoitn.setText(sum);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void loadTest() {
        try {
            rs.first();
            lblMaCH.setText("Câu " + rs.getString("MaCH") + ":");
            rdbOption1.setText(rs.getString("DapAnA"));
            rdbOption2.setText(rs.getString("DapAnB"));
            rdbOption3.setText(rs.getString("DapAnC"));
            rdbOption4.setText(rs.getString("DapAnD"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH));
            lblImg.setIcon(imgIcon);
            img_DATA = img;
            if (rdbOption1.equals(rs.getString(8))) {
                rdbOption1.setBackground(Color.green);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void loadInfDKT() {
        try {
            String url = "Select * from ChuDe";
            pst = con.prepareStatement(url);
            rs = pst.executeQuery();
            while (rs.next()) {
                lblMaDKT.setText(rs.getString("MaCD"));
                lblTenChuDe.setText(rs.getString("TenChuDe"));
            }
        } catch (Exception e) {
        }
    }

    public void loadInfUser() {
        try {
            String url = "Select top 1 * from NguoiDung";
            pst = con.prepareStatement(url);
            rs = pst.executeQuery();
            while (rs.next()) {
                lblMaND.setText(rs.getString("MaND"));
                lblHoTen.setText(rs.getString("HoTen"));
            }
        } catch (Exception e) {
        }
    }

    public void test() {
        try {
            String url = "Select top 1 CauTraLoi from cauhoi where chude = 'Bugs and insects'";
            pst = con.prepareStatement(url);

            while (rs.next()) {
                String answer = rs.getString("CauTraLoi");
                if (rdbOption1.equals(answer)) {
                    rdbOption1.setBackground(Color.green);
                }
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void sumQuiz() {
        try {
            int temp = 0;
            while (rs.next()) {
                temp += 1;
            }
            String sum = Integer.toString(temp);
            lblSumMark.setText(sum);
        } catch (Exception e) {
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Option;
    private javax.swing.JProgressBar ProgressBar1;
    private javax.swing.JPanel Top;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbTopic;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCau1;
    private javax.swing.JLabel lblCau10;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMaCH;
    private javax.swing.JLabel lblMaDKT;
    private javax.swing.JLabel lblMaND;
    private javax.swing.JLabel lblSumMark;
    private javax.swing.JLabel lblSumPoitn;
    private javax.swing.JLabel lblSumQuiz;
    private javax.swing.JLabel lblSumTime;
    private javax.swing.JLabel lblTenChuDe;
    private javax.swing.JLabel lblTime;
    private javax.swing.JRadioButton rdbOption1;
    private javax.swing.JRadioButton rdbOption2;
    private javax.swing.JRadioButton rdbOption3;
    private javax.swing.JRadioButton rdbOption4;
    // End of variables declaration//GEN-END:variables
}
